{% set version = "0.18.1" %}

{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  fn: scikit-learn-{{ version }}.tar.gz
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: f861b988089b0ccc74c0be10a105ed2fe34a2a608d6f19e67147b4da26e39ac3
  patches:
    # TODO: Remove this patch when 0.19 is released
    - skip-tests-failing-on-0.18.1.patch

build:
  number: 200
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win or np!=112]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy
    - nose

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy

test:
  requires:
    - nose

  imports:
    - sklearn

  commands:
    - nosetests sklearn --exe

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
