{% set version = "0.20.3" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: cadeefa9a824671bdcad790a075efbaa0d5a00458c43c9b4ce7110b129df7b10

build:
  number: 1
  script:
    - rm $PREFIX/include/cblas.h      # [not win]
    - del /f %LIBRARY_INC%\cblas.h    # [win]
    # pip installing this fails randonly :-/
    - "{{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython
    - libcblas
    - setuptools
    - numpy
    - scipy
    - pytest
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  requires:
    - pytest
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - pytest --verbose --pyargs sklearn

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
