{% set version = "0.19.2" %}
{% set name = "scikit-learn" %}
{% set variant = "openblas" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b276739a5f863ccacb61999a3067d0895ee291c95502929b2ae56ea1f882e888

build:
  number: 200
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}
  script:
    - LDFLAGS=$(echo "${LDFLAGS}" | sed 's/-lc++//')      # [osx]
    - LDFLAGS="${LDFLAGS} -undefined dynamic_lookup -bundle"      # [osx]
    - LINKFLAGS=$(echo "${LINKFLAGS}" | sed 's/-lc++//')  # [osx]
    - unset LDFLAGS  # [linux]
    - unset LINKFLAGS  # [linux]
    - python -m pip install --no-deps --ignore-installed --build . .

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("fortran") }}
  host:
    - python
    #
    # Pin Cython to workaround a known issue.
    #
    # xref: https://github.com/scikit-learn/scikit-learn/issues/10342
    #
    - cython 0.27.*
    - pip
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - numpy
    - scipy
    - nose
  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - {{ pin_compatible("numpy") }}
    - scipy

test:
  requires:
    - nose
  imports:
    - sklearn
  commands:
    - nosetests sklearn --exe

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
