{% set version = "0.22.2.post1" %}
{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: c6c57326941b1854112e6730961f31995ea60fa254e79daae1994e4cd5cb6f44
  patches:
    - gh17054.patch

build:
  number: 1
  skip: true  # [py2k]
  script:
    - rm $PREFIX/include/cblas.h  # [not win]
    - del /f %LIBRARY_INC%\cblas.h  # [win]
    # build the C files in parallel. This helps beat the
    # time limit consistently on drone.io
    - {{ PYTHON }} setup.py build_ext -j{{ CPU_COUNT }}
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.28.5
    - libcblas
    - numpy
    - scipy >=0.17.0
    - joblib >=0.11
  run:
    - python
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy
    - joblib >=0.11


# Some tests take alot of memory, and seem to cause segfaults when memory runs out
{% set test_cpus = CPU_COUNT %}  # [not (aarch64 or ppc64le)]
{% set test_cpus = 4 %}  # [ppc64le]
{% set test_cpus = 8 %}  # [aarch64]

{% set tests_to_skip = "_not_a_real_test" %}
# Can fail on aarch64 and ppc64le -- https://github.com/scikit-learn/scikit-learn/issues/15821
{% set tests_to_skip = tests_to_skip + " or test_uniform_grid" %}                         # [aarch64 or ppc64le]
# Occasionally fails on aarch64 -- https://github.com/scikit-learn/scikit-learn/issues/15825
{% set tests_to_skip = tests_to_skip + " or test_unreachable_accuracy" %}                 # [aarch64]

test:
  requires:
    - pytest >=3.3.0
    - cython >=0.28.5
    - pytest-xdist
    - pytest-timeout
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - set OMP_NUM_THREADS=1               # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - export OMP_NUM_THREADS=1            # [not win]
    - pytest --timeout 300 -n {{ test_cpus }} --verbose --pyargs sklearn -k "not ({{ tests_to_skip }})"

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
    - glemaitre
    - jeremiedbb
