{% set version = "0.18rc2" %}

{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  fn: scikit-learn-{{ version }}.tar.gz
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  md5: 841dd8b665852edcb72cd956a624f524

build:
  number: 203
  # We lack openblas on Windows, and therefore can't build numpy there either currently.
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cython
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy
    - nose

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.19|0.2.19.*
    - numpy x.x
    - scipy

test:
  requires:
    - nose

  imports:
    - sklearn

  commands:
    - echo "this is the best test ever"

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - jakirkham
    - ogrisel
