{% set version = "0.21.3" %}
{% set variant = "openblas" %}

package:
  name: scikit-learn
  version: {{ version }}

source:
  url: https://github.com/scikit-learn/scikit-learn/archive/{{ version }}.tar.gz
  sha256: 260f66e9c643207fe8cfe0995242060fdb14137b5e69a8dd273ac463b7e9426b

build:
  number: 0
  skip: True  # [py2k]
  script:
    - rm $PREFIX/include/cblas.h  # [not win]
    - del /f %LIBRARY_INC%\cblas.h  # [win]
    - "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
  host:
    - python
    - pip
    - llvm-openmp  # [osx]
    - cython >=0.28.5
    - libcblas
    - numpy
    - scipy >=0.17.0
    - joblib >=0.11
  run:
    - python
    - llvm-openmp  # [osx]
    - {{ pin_compatible('numpy') }}
    - scipy
    - joblib >=0.11

test:
  requires:
    - pytest >=3.3.0
    - cython >=0.28.5
  imports:
    - sklearn
  commands:
    - set OPENBLAS_NUM_THREADS=1          # [win]
    - export OPENBLAS_NUM_THREADS=1       # [not win]
    - pytest --verbose --pyargs sklearn  # [not (aarch64 or ppc64le)]
    - pytest --verbose --pyargs sklearn -k 'not test_estimate_bandwidth_1sample'  # [aarch64 or ppc64le]

about:
  home: http://scikit-learn.org/
  license: BSD 3-Clause
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining

extra:
  recipe-maintainers:
    - amueller
    - astaric
    - jakirkham
    - ogrisel
    - ocefpaf
    - lesteve
    - jnothman
    - rth
    - adrinjalali
